INSERT INTO Filiere (id, label) VALUES
(1, 'Informatique'),
(2, 'Industriel'),
(3, 'Cybersécurité'),
(4, 'Réseaux'),
(5, 'Environnement'),
(6, 'Électrique');

INSERT INTO Questions (id, label) VALUES
('extraversion_1', 'Je me sens plein(e) d’énergie lorsque je suis entouré(e) de plusieurs personnes.'),
('extraversion_2', 'Je prends souvent la parole lors de réunions ou de discussions de groupe.'),
('extraversion_3', 'J’apprécie d’organiser ou de participer à des événements sociaux.'),
('extraversion_4', 'Je préfère les environnements calmes plutôt que les endroits animés.'),
('extraversion_5', 'Je m’ennuie vite si je ne suis pas en contact avec d’autres personnes.'),
('extraversion_6', 'Je cherche activement à rencontrer de nouvelles personnes.'),
('extraversion_7', 'Je préfère passer mes soirées à discuter avec des amis plutôt que seul(e) chez moi.'),
('extraversion_8', 'Je suis plus à l’aise lorsque je travaille seul(e) ou en équipe réduite.'),
('extraversion_9', 'J’aime être au centre de l’attention.'),
('extraversion_10', 'Je me sens parfois fatigué(e) après de longues interactions sociales.'),

('ouverture_1', 'J’aime découvrir de nouvelles idées, méthodes ou approches dans mes études ou projets.'),
('ouverture_2', 'Je suis curieux(se) et je peux facilement m’enthousiasmer pour un sujet inconnu.'),
('ouverture_3', 'Je préfère suivre des procédures déjà établies plutôt que d’innover.'),
('ouverture_4', 'Je m’intéresse à des domaines artistiques ou culturels (musique, peinture, littérature…).'),
('ouverture_5', 'J’aime remettre en question les façons de faire traditionnelles.'),
('ouverture_6', 'Je suis souvent en quête de nouvelles expériences ou de voyages.'),
('ouverture_7', 'Je reste méfiant(e) vis-à-vis de ce qui sort de l’ordinaire ou de ce que je connais déjà.'),
('ouverture_8', 'Je me considère comme quelqu’un de créatif(ve).'),
('ouverture_9', 'Je cherche à comprendre les choses en profondeur plutôt que de me contenter d’explications superficielles.'),
('ouverture_10', 'Je me sens facilement limité(e) par la routine et la répétition.'),

('conscienciosite_1', 'Je fais habituellement des listes de tâches et je respecte un planning.'),
('conscienciosite_2', 'Je remets souvent des tâches à plus tard.'),
('conscienciosite_3', 'Je suis très attentif(ve) à la qualité et aux détails dans ce que je fais.'),
('conscienciosite_4', 'Je planifie à l’avance pour éviter les imprévus autant que possible.'),
('conscienciosite_5', 'J’ai parfois du mal à rester concentré(e) sur un projet jusqu’à ce qu’il soit terminé.'),
('conscienciosite_6', 'On peut compter sur moi pour respecter mes engagements.'),
('conscienciosite_7', 'Je me laisse souvent distraire par des éléments extérieurs (internet, discussions…).'),
('conscienciosite_8', 'Je persévère même quand un exercice ou un projet s’avère difficile.'),
('conscienciosite_9', 'Je tiens mes affaires (bureau, chambre, etc.) dans un ordre précis.'),
('conscienciosite_10', 'Je trouve difficile de maintenir un niveau constant d’effort sur une longue période.'),


('stabilite_emotionnelle_1', 'J’ai tendance à être plutôt calme et à ne pas stresser facilement.'),
('stabilite_emotionnelle_2', 'Je m’inquiète beaucoup des petits détails qui pourraient mal tourner.'),
('stabilite_emotionnelle_3', 'Je gère bien la pression et les délais serrés.'),
('stabilite_emotionnelle_4', 'Je ressens parfois des sautes d’humeur rapides et intenses.'),
('stabilite_emotionnelle_5', 'J’arrive à garder mon sang-froid en situation de conflit ou d’urgence.'),
('stabilite_emotionnelle_6', 'Je panique facilement quand je me sens débordé(e).'),
('stabilite_emotionnelle_7', 'Je suis capable de relativiser quand un résultat n’est pas conforme à mes attentes.'),
('stabilite_emotionnelle_8', 'Je me sens souvent anxieux(se) même lorsque tout se passe bien.'),
('stabilite_emotionnelle_9', 'Je trouve qu’il est facile de rester positif(ve) et motivé(e) malgré les difficultés.'),
('stabilite_emotionnelle_10', 'J’ai besoin de temps pour me remettre d’un échec ou d’une critique négative.'),

('agreabilite_1', 'Je fais le maximum pour éviter les conflits et maintenir un climat de travail agréable.'),
('agreabilite_2', 'Je peux être assez compétitif(ve) et parfois insister sur mon point de vue.'),
('agreabilite_3', 'J’aime aider les autres, même si cela me demande un effort supplémentaire.'),
('agreabilite_4', 'Je suis prêt(e) à faire des compromis pour résoudre un désaccord.'),
('agreabilite_5', 'J’ai tendance à dire les choses franchement, même si cela peut blesser.'),
('agreabilite_6', 'Les gens me décrivent souvent comme bienveillant(e) et prévenant(e).'),
('agreabilite_7', 'Je préfère coopérer plutôt que de rivaliser.'),
('agreabilite_8', 'Je pense que la gentillesse peut être perçue comme une faiblesse.'),
('agreabilite_9', 'Je respecte les idées et sentiments d’autrui, même si je ne les partage pas.'),
('agreabilite_10', 'J’ai parfois du mal à pardonner ou à passer outre une faute qu’on a commise envers moi.'),

('motivation_1', 'Je suis motivé(e) par l’idée de résoudre des problèmes techniques complexes.'),
('motivation_2', 'J’ai besoin de ressentir un impact concret de mon travail sur la société ou l’environnement.'),
('motivation_3', 'Je préfère travailler sur des projets où l’innovation et la créativité sont encouragées.'),
('motivation_4', 'J’apprécie de travailler en équipe et de collaborer avec différentes personnes.'),
('motivation_5', 'Je recherche des projets où je peux améliorer en continu les processus ou systèmes existants.'),
('motivation_6', 'Je suis stimulé(e) par l’idée de découvrir et maîtriser de nouvelles technologies.'),
('motivation_7', 'La stabilité financière et la sécurité de l’emploi sont au cœur de mes priorités.'),
('motivation_8', 'J’adore relever des défis, même si cela implique de sortir de ma zone de confort.'),
('motivation_9', 'Je veux voir rapidement des résultats concrets de mon travail.'),
('motivation_10', 'Je préfère des responsabilités claires et un cadre de travail bien défini.'),
('motivation_11', 'Je suis prêt(e) à consacrer beaucoup de temps si le projet me passionne vraiment.'),
('motivation_12', 'Je trouve plus de satisfaction dans l’excellence et la progression continue.'),

('interest_1', 'La conception de logiciels, la programmation et les algorithmes m’attirent fortement.'),
('interest_2', 'J’aime comprendre et mettre en place des stratégies pour optimiser la production ou la logistique.'),
('interest_3', 'Assurer la sécurité de systèmes informatiques contre des attaques me passionne.'),
('interest_4', 'Je souhaite travailler sur la conception ou la maintenance de réseaux et d’infrastructures de communication.'),
('interest_5', 'J’ai un fort intérêt pour la protection de l’environnement, la gestion des ressources et le développement durable.'),
('interest_6', 'La conception et la maintenance de systèmes électriques/électroniques m’intéressent particulièrement.'),
('interest_7', 'Je me vois bien dans un poste où la gestion de projet et la coordination d’équipes sont essentielles.'),
('interest_8', 'Je préfère me concentrer sur des tâches techniques plutôt que sur la gestion humaine.'),
('interest_9', 'Je suis curieux(se) au sujet des menaces informatiques, de la cryptographie et de la cyberdéfense.'),
('interest_10', 'Je souhaite trouver des solutions concrètes pour réduire l’empreinte écologique d’une organisation.'),
('interest_11', 'Je m’imagine développer des applications ou des logiciels grand public ou professionnels.'),
('interest_12', 'Je veux comprendre et gérer la complexité des systèmes électriques (énergies renouvelables, smart grids...).'),

('fam_1', 'Ma famille m’encourage fortement à choisir une filière spécifique.'),
('fam_2', 'Les attentes de mes parents influencent grandement mes décisions d’orientation.'),
('fam_3', 'Je me sens libre de suivre ma passion, peu importe l’avis de ma famille.'),
('fam_4', 'Je reçois un soutien moral et/ou financier important de ma famille pour mes études.'),
('fam_5', 'Je sens que la réussite professionnelle selon les critères familiaux est plus importante que mon propre intérêt.');

