INSERT INTO Questions (id, label) VALUES
('extraversion_1', 'Question sur lextraversion 1'),
('extraversion_2', 'Question sur lextraversion 2'),
('extraversion_3', 'Question sur lextraversion 3'),
('extraversion_4', 'Question sur lextraversion 4'),
('extraversion_5', 'Question sur leextraversion 5'),
('extraversion_6', 'Question sur leextraversion 6'),
('extraversion_7', 'Question sur leextraversion 7'),
('extraversion_8', 'Question sur lextraversion 8'),
('extraversion_9', 'Question sur lextraversion 9'),
('extraversion_10', 'Question sur lextraversion 10'),

('ouverture_1', 'Question sur louverture 1'),
('ouverture_2', 'Question sur louverture 2'),
('ouverture_3', 'Question sur louverture 3'),
('ouverture_4', 'Question sur louverture 4'),
('ouverture_5', 'Question sur louverture 5'),
('ouverture_6', 'Question sur louverture 6'),
('ouverture_7', 'Question sur louverture 7'),
('ouverture_8', 'Question sur louverture 8'),
('ouverture_9', 'Question sur louverture 9'),
('ouverture_10', 'Question sur louverture 10'),

('conscienciosite_1', 'Question sur la conscience 1'),
('conscienciosite_2', 'Question sur la conscience 2'),
('conscienciosite_3', 'Question sur la conscience 3'),
('conscienciosite_4', 'Question sur la conscience 4'),
('conscienciosite_5', 'Question sur la conscience 5'),
('conscienciosite_6', 'Question sur la conscience 6'),
('conscienciosite_7', 'Question sur la conscience 7'),
('conscienciosite_8', 'Question sur la conscience 8'),
('conscienciosite_9', 'Question sur la conscience 9'),
('conscienciosite_10', 'Question sur la conscience 10'),

('stabilite_emotionnelle_1', 'Question sur la stabilité émotionnelle 1'),
('stabilite_emotionnelle_2', 'Question sur la stabilité émotionnelle 2'),
('stabilite_emotionnelle_3', 'Question sur la stabilité émotionnelle 3'),
('stabilite_emotionnelle_4', 'Question sur la stabilité émotionnelle 4'),
('stabilite_emotionnelle_5', 'Question sur la stabilité émotionnelle 5'),
('stabilite_emotionnelle_6', 'Question sur la stabilité émotionnelle 6'),
('stabilite_emotionnelle_7', 'Question sur la stabilité émotionnelle 7'),
('stabilite_emotionnelle_8', 'Question sur la stabilité émotionnelle 8'),
('stabilite_emotionnelle_9', 'Question sur la stabilité émotionnelle 9'),
('stabilite_emotionnelle_10', 'Question sur la stabilité émotionnelle 10'),

('agreabilite_1', 'Question sur lagréabilité 1'),
('agreabilite_2', 'Question sur lagréabilité 2'),
('agreabilite_3', 'Question sur lagréabilité 3'),
('agreabilite_4', 'Question sur lagréabilité 4'),
('agreabilite_5', 'Question sur lagréabilité 5'),
('agreabilite_6', 'Question sur lagréabilité 6'),
('agreabilite_7', 'Question sur lagréabilité 7'),
('agreabilite_8', 'Question sur lagréabilité 8'),
('agreabilite_9', 'Question sur lagréabilité 9'),
('agreabilite_10', 'Question sur lagréabilité 10'),

('motivation_1', 'Question sur la motivation 1'),
('motivation_2', 'Question sur la motivation 2'),
('motivation_3', 'Question sur la motivation 3'),
('motivation_4', 'Question sur la motivation 4'),
('motivation_5', 'Question sur la motivation 5'),
('motivation_6', 'Question sur la motivation 6'),
('motivation_7', 'Question sur la motivation 7'),
('motivation_8', 'Question sur la motivation 8'),
('motivation_9', 'Question sur la motivation 9'),
('motivation_10', 'Question sur la motivation 10'),
('motivation_11', 'Question sur la motivation 11'),
('motivation_12', 'Question sur la motivation 12'),

('interest_1', 'Question sur lintérêt 1'),
('interest_2', 'Question sur lintérêt 2'),
('interest_3', 'Question sur lintérêt 3'),
('interest_4', 'Question sur lintérêt 4'),
('interest_5', 'Question sur lintérêt 5'),
('interest_6', 'Question sur lintérêt 6'),
('interest_7', 'Question sur lintérêt 7'),
('interest_8', 'Question sur lintérêt 8'),
('interest_9', 'Question sur lintérêt 9'),
('interest_10', 'Question sur lintérêt 10'),
('interest_11', 'Question sur lintérêt 11'),
('interest_12', 'Question sur lintérêt 12'),

('fam_1', 'Question sur la famille 1'),
('fam_2', 'Question sur la famille 2'),
('fam_3', 'Question sur la famille 3'),
('fam_4', 'Question sur la famille 4'),
('fam_5', 'Question sur la famille 5');
